export { $host, $authHost } from "./http"
export { createFeedback } from "./feedbackApi"
export { createGoal, updateGoal, deleteGoal, getGoals, getGoal, getGoalProgress, createGoalItem, updateGoalItem, updateGoalItemStatus, deleteGoalItem, getGoalItems } from "./goalApi"
export { createTask, updateTask, updateTaskStatus, deleteTask, getTask } from "./taskApi"
export { registration, login, check, getInfo, updateInfo, updateImage, deleteImage, deleteAccount } from "./userApi"
export {getUsers, createUser, updateUser, deleteUser, updateFeedbackStatus, getFeedbacks}from "./adminApi"