export const INFO_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const ADMIN_USER_ROUTE = '/users'
export const ADMIN_FEEDBACK_ROUTE = '/feedbacks'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const WELCOME_ROUTE = '/welcome'
export const PROFILE_ROUTE = '/profile'
export const TASKS_ROUTE = '/task'
export const GOALS_ROUTE = '/goal'
export const FEEDBACK_ROUTE = '/feedback'
// Добавить главную страницу с общей информацией