export {
    ADMIN_FEEDBACK_ROUTE,
    ADMIN_ROUTE,
    ADMIN_USER_ROUTE,
    FEEDBACK_ROUTE,
    GOALS_ITEM_ROUTE,
    GOALS_ROUTE,
    INFO_ROUTE,
    LOGIN_ROUTE,
    PROFILE_ROUTE,
    REGISTRATION_ROUTE,
    TASKS_ROUTE,
    WELCOME_ROUTE
} from './routes'