name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for frontend
        working-directory: client
        run: |
          npm install

      - name: Run lint for frontend
        working-directory: client
        run: |
          npm run lint

      - name: Run Steiger for frontend
        working-directory: client
        run: |
          npm run lint:steiger

      - name: Typecheck for frontend
        working-directory: client
        run: |
          npm run typecheck

      - name: Build frontend
        working-directory: client
        run: |
          npm run build

      - name: Install dependencies for backend
        working-directory: server
        run: |
          npm install

      - name: Run lint for backend
        working-directory: server
        run: |
          npm run lint

      - name: Run migrations for backend
        working-directory: server
        run: |
          npm run migrate

      - name: Start backend in dev mode
        working-directory: server
        run: |
          npm run dev
